CXX = clang++
CXXFLAGS += -Iinclude -std=c++14 -stdlib=libc++ -Wall -Wextra -O0 -g
LDFLAGS += -std=c++14 -stdlib=libc++ -lc++abi
TESTOBJS = huffman_tree.o decoder.o encoder.o binary_file_reader.o binary_file_writer.o frequency.o
include Makefile.proxy
