CXX = clang++
CXXFLAGS += -Iinclude -std=c++14 -stdlib=libc++ -Wall -Wextra
LDFLAGS += -stdlib=libc++ -lc++abi -lpng

TESTOBJS = quadtree.o quadtree_given.o epng.o rgba_pixel.o proxy_fit_curve.o
include Makefile.proxy
